"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var core_1 = require("@angular/core");
var http_1 = require("@angular/http");
var urls_1 = require("../urls");
var GeoService = (function () {
    function GeoService(_http, _urls) {
        this._http = _http;
        this._urls = _urls;
        this.cities = ["Алушта", "Армянськ", "Красноперекопськ", "Джанкой", "Євпаторія", "Керч", "Саки", "Сімферополь", "Судак", "Феодосія", "Ялта", "Вінниця",
            "Жмеринка", "Козятин", "Ладижин", "Могилів-Подільський", "Хмільник", "Володимир-Волинський", "Ковель", "Луцьк", "Нововолинськ", "Вільногірськ", "Кам'янське", "Дніпро",
            "Жовті Води", "Кривий Ріг", "Марганець", "Нікополь", "Новомосковськ", "Покров", "Павлоград", "Першотравенськ", "Синельникове", "Тернівка", "Авдіївка", "Бахмут",
            "Вугледар", "Горліка", "Дебальцеве", "Торецьк", "Мирноград", "Добропілля", "Докучаєвськ", "Донецьк", "Дружківка", "Жданівка", "Єнакієве", "Хрестівка", "Костянтинівка",
            "Краматорськ", "Лиман", "Покровськ", "Макіївка", "Маріуполь", "Новогродівка", "Селидове", "Слов'янськ", "Сніжне", "Чистякове", "Харцизьк", "Шахтарськ", "Ясинувата",
            "Бердичів", "Житомир", "Коростень", "Малин", "Новоград-Волинський", "Берегове", "Мукачеве", "Ужгород", "Хуст", "Чоп", "Бердянськ", "Енергодар", "Запоріжжя",
            "Мелітополь", "Токмак", "Болехів", "Івано-Франківськ", "Калуш", "Коломия", "Яремче", "Бориспіль", "Березань", "Біла Церква", "Бровари", "Буча", "Васильків",
            "Ірпінь", "Обухів", "Переяслав-Хмельницький", "Прип'ять", "Ржищів", "Славутич", "Фастів", "Знам'янка", "Кропивницький", "Олександрія", "Світловодськ", "Алчевськ",
            "Антрацит", "Брянка", "Голубівка", "Хрустальний", "Сорокине", "Лисичанськ", "Луганськ", "Первомайськ", "Ровеньки", "Рубіжне", "Довжанськ", "Сєвєродонецьк", "Кадіївка",
            "Борислав", "Дрогобич", "Львів", "Моршин", "Новий Розділ", "Самбір", "Стрий", "Трускавець", "Червоноград", "Вознесенськ", "Миколаїв", "Очаків", "Первомайськ",
            "Южноукраїнськ", "Білгород-Дністровський", "Ізмаїл", "Чорноморськ", "Подільськ", "Одеса", "Теплодар", "Южне", "Горішні Плавні", "Кременчук", "Лубни", "Миргород",
            "Полтава", "Дубно", "Вараш", "Острог", "Рівне", "Охтирка", "Глухів", "Конотоп", "Лебедин", "Ромни", "Суми", "Шостка", "Тернопіль", "Бережани", "Кременець", "Чортків",
            "Ізюм", "Куп'янськ", "Лозова", "Люботин", "Первомайськ", "Харків", "Чугуїв", "Каховка", "Нова Каховка", "Херсон", "Кам'янець-Подільський", "Нетішин", "Славута",
            "Старокостянтинів", "Хмельницький", "Шепетівка", "Ватутіне", "Золотоноша", "Канів", "Сміла", "Умань", "Черкаси", "Новодністровськ", "Чернівці", "Ніжин", "Прилуки", "Чернігів"
        ];
    }
    GeoService.prototype.getCountries = function () {
        return [
            "Afghanistan",
            "Albania",
            "Algeria",
            "American Samoa",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antarctica",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Беларусь",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Bouvet Island",
            "Brazil",
            "British Indian Ocean Territory",
            "Brunei Darussalam",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cape Verde",
            "Cayman Islands",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Christmas Island",
            "Cocos (Keeling) Islands",
            "Colombia",
            "Comoros",
            "Congo",
            "Congo, the Democratic Republic of the",
            "Cook Islands",
            "Costa Rica",
            "Cote D'Ivoire",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
            "Falkland Islands (Malvinas)",
            "Faroe Islands",
            "Fiji",
            "Finland",
            "France",
            "French Guiana",
            "French Polynesia",
            "French Southern Territories",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Gibraltar",
            "Greece",
            "Greenland",
            "Grenada",
            "Guadeloupe",
            "Guam",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Heard Island and Mcdonald Islands",
            "Holy See (Vatican City State)",
            "Honduras",
            "Hong Kong",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran, Islamic Republic of",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Korea, Democratic People's Republic of",
            "Korea, Republic of",
            "Kuwait",
            "Kyrgyzstan",
            "Lao People's Democratic Republic",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libyan Arab Jamahiriya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macao",
            "Macedonia, the Former Yugoslav Republic of",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "Mexico",
            "Micronesia, Federated States of",
            "Moldova, Republic of",
            "Monaco",
            "Mongolia",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "Netherlands Antilles",
            "New Caledonia",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Niue",
            "Norfolk Island",
            "Northern Mariana Islands",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestinian Territory, Occupied",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Pitcairn",
            "Poland",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Reunion",
            "Romania",
            "Rwanda",
            "Saint Helena",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Pierre and Miquelon",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia and Montenegro",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Georgia and the South Sandwich Islands",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Svalbard and Jan Mayen",
            "Swaziland",
            "Sweden",
            "Switzerland",
            "Syrian Arab Republic",
            "Taiwan, Province of China",
            "Tajikistan",
            "Tanzania, United Republic of",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Tokelau",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Turks and Caicos Islands",
            "Tuvalu",
            "Uganda",
            "Україна",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "United States Minor Outlying Islands",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Venezuela",
            "Viet Nam",
            "Virgin Islands, British",
            "Virgin Islands, US",
            "Wallis and Futuna",
            "Western Sahara",
            "Yemen",
            "Zambia",
            "Zimbabwe"
        ];
    };
    GeoService.prototype.getCities = function (country, query) {
        if (country !== 'Україна')
            return [];
        return this.cities.filter(function (item) { return item.toLowerCase().indexOf(query.toLowerCase()) > -1; });
    };
    return GeoService;
}());
GeoService = __decorate([
    core_1.Injectable(),
    __metadata("design:paramtypes", [http_1.Http, urls_1.UrlsService])
], GeoService);
exports.GeoService = GeoService;
//# sourceMappingURL=geo.service.js.map